title: "AIMATX Careers"
show_title: false  # Many Jekyll themes have this option
description: "Join us in building the future of materials science"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
show_downloads: false
